spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baloo
    username: root
    password: ueducation
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/baloo
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/baloo

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql